### ISSUE TITLE
More permissive license

### ISSUE THREAD

**Issue by xternalz** [yan-hao-tian/VW#17]
Hi, thanks for this nice work. I know that this repository is licensed under CC Attribution-NonCommercial 4.0 and I respect your decision on that. For this to have a greater impact to the community, would you consider adopting a more permissive license (MIT or Apache 2.0) for this? Mask2Former is an example of high-impact work that is licensed under the MIT license.

**Comment by yan-hao-tian** [comment]
Thanks for the advice. 😊
