### ISSUE TITLE
为什么VWFormer两个版本的不一样

### ISSUE THREAD

**Issue by sunhanzhang** [yan-hao-tian/VW#19]
为什么对于cityscapes数据集的VWFormer的这个代码，跟另外一个VWFormer的代码不一样？有人知道原因吗？？？

**Comment by yan-hao-tian** [comment]
差别不太大，一个是用mmcv的nonlocal实现attention的计算，一个是用torch的multiheadattention实现attention的计算。有时间我会对齐一下，前者效果其实会更好一点。
