### ISSUE TITLE
No MLP Mixer code found

### ISSUE THREAD

**Issue by vsingh1998** [yan-hao-tian/VW#21]
Hi, 

In your first draft of paper on Arxiv, you mentioned that you are using MLP mixer to mix the channels but I don't see any code that uses MLP Mixer. Can you please clarify? If you removed the MLP Mixer, what was the reason behind it?

**Comment by yan-hao-tian** [comment]
hi, Mr. Singh. MLP Mixer's effectiveness is not solid, so it is not included in the newest version accepted by ICLR. Its code can be found in the "oldversion" branch.
