### ISSUE TITLE
Segformer Config File

### ISSUE THREAD

**Issue by hhuzzz** [yan-hao-tian/VW#22]
哈喽，请问能提供一下SegFormer-B0的config文件吗，因为我按论文里的说法配置后效果不好，可能是我没写好配置文件的原因。

> The new flow of channels is 128 (output of multi-layer aggregation)→ 512(concatenation of learned multi-scale representations)→ 128(output of multiscale aggregation)→ 128 + 32 = 160(concatenation of LLE)→ 128(final output of VWFormer)

**Comment by yan-hao-tian** [comment]
哈喽 抱歉晚回复，最近有点忙。。。您可以先看一下oldversion分支，模型架构有点区别，但性能差不多
