### ISSUE TITLE
Loss nan

### ISSUE THREAD

**Issue by xinyu-laura** [yan-hao-tian/VW#3]
Hi, I used the lawin decoder and MiT-B2 as Encoder to train on Cityscapes, but got Nan Loss after about 16000 iterations. Could you please help me to check the code for the decoder again?

**Comment by ydhongHIT** [comment]
> Hi, I used the lawin decoder and MiT-B2 as Encoder to train on Cityscapes, but got Nan Loss after about 16000 iterations. Could you please help me to check the code for the decoder again?

Hi, how about your performance? I trained the MiT-B2 + lawin with 80k iterations but got no obvious improvement.
