### ISSUE TITLE
FULL CODE

### ISSUE THREAD

**Issue by HerrYu123** [yan-hao-tian/VW#4]
Congratulations to such an excellent job! I'm looking forward to your project of the full code. Thanks in advance!

**Comment by gaowq2017** [comment]
The same looking forward to openning the full code!

**Comment by satpalsr** [comment]
Hey @yan-hao-tian , Any timeline for the release of code and model weights?

**Comment by yan-hao-tian** [comment]
Hi guys, the full code is available.
