### ISSUE TITLE
imagenet train code

### ISSUE THREAD

**Issue by endaoguansanlu** [yan-hao-tian/VW#9]
Hi! Thanks for your excellent work, do you have a plan to release the imagenet pre-train code? ^ _ ^

**Comment by yan-hao-tian** [comment]
https://drive.google.com/drive/folders/1b7bwrInTW4VLEm27YawHOAMSMikga2Ia?usp=sharing
Hi! BTW, the pretrained MITs are published by SegFormer (github.com/NVlabs/SegFormer). The pre-training code may be found there.
